# simple make file to make the inner project simple_start

simpleStart: 
	g++ ./simple_main.cc ./neural/neural.cc  -o ../../build/simple_start/simple_main

test:
	../../build/simple_start/simple_main



