# simple make file to make the inner project simple_start

CC=g++

simpleStart: 
	$(CC) -I/usr/local/Cellar/glog/0.3.4/include -L/usr/local/Cellar/glog/0.3.4/lib -lglog ./simple_main.cc ./neural/neural.cc  -o ../../build/simple_start/simple_main

test:
	../../build/simple_start/simple_main



